### PR TITLE
Analysis #1 Set up program to create baseline table for units and household affordability

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo ready for review. I'm not sure why there are so many hh_inc not coded after the Hud_inc_reghsg macro. cc @lhendey

**Comment by maggiesu0725** [comment]
@rpitingolo I just added Housing_needs_baseline_units_availability for calculating the availability(who lives in those units) of units at each affordable level. cc @lhendey

**Comment by rpitingolo** [comment]
@maggiesu0725 there is a typo in %Hud_inc_RegHsg that is causing it sometimes out create the variable hud_inc and sometime hudinc.

**Comment by maggiesu0725** [comment]
@rpitingolo I don't think we need vacant unit for calculating rent burden of households by hud income level which is Housing_needs_baseline_hh. For Housing_needs_baseline_units_availability I didn't include it because vacant units are theatrically "available" for all income levels.

**Comment by maggiesu0725** [comment]
@rpitingolo macro is fixed

**Comment by rpitingolo** [comment]
@maggiesu0725 please remove the local=n option from the %DCData_lib. When it's there the program looks for the macro on the L drive which is the version with the error. 

I'm not able to get the proc tabulate to work on the _units program. Is that a table you are trying to create with this program?

**Comment by maggiesu0725** [comment]
It's working for me? I didn't output this table but it can be used for crosschecking? I can take it out.

I actually had an issue with the _units program, so I'm assigning the hudinc format to hud_inc variable, but in the summary table 'Vacant' is not showing up.

**Comment by rpitingolo** [comment]
@maggiesu0725 there is a typo in the final proc export in Housing_needs_baseline_units_availability.sas that is causing it not to run. 

To create the vacant flag on Housing_needs_baseline_units.sas use the code in the main datastep:	if vacancy in (1,2) then vacunit = 1; else vacunit = 0;

then add vacunit to the proc summary.

**Comment by rpitingolo** [comment]
@maggiesu0725 once Leah OK's the formatted tables please go ahead and merge, finalize and close this issue. If additional work needs to be done on these we will open a new issue. Thanks.

**Pull request merged**
