### PR TITLE
initial fairfax commit

### PR DESCRIPTION
**Pull request by cdavisurban**

### CODE REVIEW

**Comment by lhendey** [comment]
@cdavisurban did you add the other commit we talked about?

**Comment by cdavisurban** [comment]
@lhendey it should be up there now. I ran into trouble when doing some more cleaning of my secondary sf variable, but it should be fixed now.

**Comment by lhendey** [comment]
@cdavisurban - a few comments

General - as these files aren't that big - i'd prefer you using different names for each new data step. that way i can more easily compare the numbers of obs and variables as changes are happening. 

did you review this documentation? https://www.fairfaxcounty.gov/maps/sites/maps/files/assets/documents/dta_assessment_tables.pdf

**Comment by lhendey** [comment]
@cdavisurban for reference found this - saved to L raw folder https://planning-org-uploaded-media.s3.amazonaws.com/legacy_resources/lbcs/background/pdf/FairfaxCoExistingUses.pdf

**Comment by lhendey** [comment]
@cdavisurban - did you make all the changes I requested on preclean?

**Comment by cdavisurban** [comment]
@lhendey - I believe so! Are there changes that you wanted that you don't see?

**Comment by lhendey** [comment]
@cdavisurban i thought i left comments on your desk? I didn't see updates to preclean from yesterday.

**Comment by maggiesu0725** [comment]
@rpitingolo The program should be running with no error. I added comment to explain what each step is doing, as well as finished the merge step

**Comment by cdavisurban** [comment]
@lhendey somehow I missed those on my desk - I have updated accordingly. I also added some info as to the number of parcels that are in the BlackKnight data that are missing from the dwelling and land files

**Comment by lhendey** [comment]
@cdavisurban reviewing. 

on preclean - you confirmed this isn't an parcel id mismatch problem? 

There are 531 units in the Blacknight data that are not in the parcels data.
There are 848 units in the parcels data that are not in the BlackKnight data.

**Comment by lhendey** [comment]
@cdavisurban preclean looks good to go.

**Comment by lhendey** [comment]
@cdavisurban can you make the final tweaks to clean-fairfax today?

**Comment by cdavisurban** [comment]
@lhendey I can, I should have it done by tomorrow AM.

**Comment by lhendey** [comment]
@cdavisurban - great. i need to have all counties cleaned by tomorrow.

**Pull request merged**
