### PR TITLE
calculate calibration using exact cog 2015

### PR DESCRIPTION
**Pull request by lhendey**

### CODE REVIEW

**Comment by lhendey** [comment]
@ptatian - i used the exact 2015 COG estimates to create the new calibration factors. the output (and your checks on proc tabulate) now matches Steven's household counts in https://urbanorg.app.box.com/file/402454379812.

**Comment by lhendey** [comment]
@ptatian do you want to review this one? then i can pull a new branch and work on the tweaks for owners.

**Comment by lhendey** [comment]
@ptatian - if you can do a quick review on the change method for adjusting weights to the COG methods, i can finalize these.

**Comment by ptatian** [comment]
@lhendey Taking a look now.

**Review by ptatian — APPROVED** [review]
@lhendey This seems fine as far as I can tell. I appreciate the additional comments and it looked like the code was doing what you said it was supposed to do. 

A couple of more general observations. You should think about using formats instead of recoding vars next time. For instance, in this section, 

```
		 *rent cost categories now used in targets that provide a set of categories useable for renters and owners combined; 
			allcostlevel=.;
			if rentgrs_a<800 then allcostlevel=1;
			if 800 <=rentgrs_a<1300 then allcostlevel=2;
			if 1300 <=rentgrs_a<1800 then allcostlevel=3;
			if 1800 <=rentgrs_a<2500 then allcostlevel=4;
			if 2500 <=rentgrs_a<3500 then allcostlevel=5;
			if rentgrs_a >= 3500 then allcostlevel=6; 
```

You don't need to create the allcostlevel var. You can just apply a format to rent_grsa when you do the tabulations. Saves you coding and makes it easier to change the breaks later if you want, because you only have to modify the one format. In this program, it's pretty significant because you create several variables like this. Just something to keep in mind. 

Also, hard coding numbers is generally not a good practice. So, in this section, 

```
 %**create ratio for rent to rentgrs to adjust rents on vacant units**;
	 data Ratio;

		  set COGSarea_&year.
		    (keep= rent rentgrs pernum gq ownershpd Jurisdiction
		     where=(pernum=1 and gq in (1,2) and ownershpd in ( 22 )));
		     
		  Ratio_rentgrs_rent_&year. = rentgrs / rent;
		 
		run;

		proc means data=Ratio;
		  var  Ratio_rentgrs_rent_&year. rentgrs rent;
		run;
			%** Value copied from Proc Means output **;
		%if &year=2013 %then %let Ratio_rentgrs_rent_&year.= 1.1429187;
		%if &year=2014 %then %let Ratio_rentgrs_rent_&year.= 1.1600331;
		%if &year=2015 %then %let Ratio_rentgrs_rent_&year.= 1.1556884;
		%if &year=2016 %then %let Ratio_rentgrs_rent_&year.= 1.1425105;
		%if &year=2017 %then %let Ratio_rentgrs_rent_&year.= 1.1193682;

		%put Ratio_rentgrs_rent_&year.=&&Ratio_rentgrs_rent_&year.;
  ...
```

Instead of copying and pasting from the output, you could have done something like this. 

``` %**create ratio for rent to rentgrs to adjust rents on vacant units**;
	 data Ratio;

		  set COGSarea_&year.
		    (keep= rent rentgrs pernum gq ownershpd Jurisdiction
		     where=(pernum=1 and gq in (1,2) and ownershpd in ( 22 )));
		     
		  Ratio_rentgrs_rent_&year. = rentgrs / rent;
		 
		run;

		proc means data=Ratio;
		  var  Ratio_rentgrs_rent_&year. rentgrs rent;
		  output out=Ratio_&year (keep=Ratio_rentgrs_rent_&year.) mean=;
		run;
  ...

data Housing_needs_vacant_&year. Other_vacant_&year. ;

  set COGSvacant_&year.(keep=year serial hhwt bedrooms gq vacancy rent valueh Jurisdiction );

  if _n_ = 1 then set Ratio_rentgrs_rent_&year.;

  retain Total 1;

  *reassign vacant but rented or sold based on whether rent or value is available; 	
  vacancy_r=vacancy; 
  if vacancy=3 and rent ~= .n then vacancy_r=1; 
  if vacancy=3 and valueh ~= .u then vacancy_r=2; 
    
    ****** Rental units ******;
	 if  vacancy_r = 1 then do;
	    Tenure = 1;
	    
	    	** Impute gross rent for vacant units **;
	  		rentgrs = rent*Ratio_rentgrs_rent_&year;

  ...
```

The `if _n_ = 1 then set ... ;` statement is a SAS trick for merging a one obs data set onto another data set with many obs. Just one less thing to remember to alter if the data change for some reason.

**Comment by lhendey** [comment]
@ptatian I incorporated your suggested changes to set the mean rent ratio for the vacant units rather than hard coding it. i left the allcostlevel coding alone.

**Pull request merged**
