### PR TITLE
Analysis #66 clean geographical data

### PR DESCRIPTION
**Pull request by sstrochak**
The purpose of `clean-node-geographies.Rmd` is to walk through the process of creating the buffered layer that will determine which areas get upzoned/how many units we can produce from upzoning. The result is the `get_node_geography()` function.

@awunderground do you have time to take a look at this? It is a bit of a complicated function so I would love your eyes, if possible. 
@cdavisurban would be nice to get your thoughts also. 

cc @lhendey

### CODE REVIEW

**Comment by sstrochak** [comment]
need this reviewed today, if anyone has a chance.

**Comment by cdavisurban** [comment]
@sstrochak I took a look, looks good to me. I committed two very minor cosmetic changes, but the function works and I don't see any issues.

**Comment by sstrochak** [comment]
@cdavisurban thanks!

@lhendey do you want to take a look? if not, ready to merge

**Comment by lhendey** [comment]
@sstrochak - go ahead and merge

**Pull request merged**
