### PR TITLE
Revise data for housing market analysis

### PR DESCRIPTION
**Pull request by ptatian**

### CODE REVIEW

**Comment by ptatian** [comment]
@lhendey Would appreciate it if you would please review these changes, particularly to the housing cost calculations in **Prog\Housing market analysis.sas**. Thank you.

**Comment by lhendey** [comment]
@ptatian taking a look now.

**Comment by ptatian** [comment]
Thanks, @lhendey. 

If you don't see an adjustment for Loudoun, then it isn't there. What adjustment are we supposed to be making?

Yes, I agree that adjustment should have been documented. We aren't using the rent burden calculations from this program any more but, still, you are right. 

Yes, should have used CUUR0000SA0L2 for adjusting housing costs. 

We use that because I wanted to make sure the counts aligned with the Census 2017 estimates and Census does not estimate households directly. They estimate housing units. But, I think in the end it wasn't necessary because Yipeng said the IPUMS weights matched the 2017 estimates already.

**Comment by lhendey** [comment]
@ptatian  - adjustments for Loudoun puma - in 2000/2010 there is one PUMA for 4 counties including Loudoun. after 2012 - Loudoun has several of its own PUMAs and no longer with Fauquier, et al.  Would need to adjust your unit counts.

**Comment by ptatian** [comment]
@lhendey I made the changes on the Loudoun Co PUMA weights and CPI series for housing costs.

**Pull request merged**
