### PR TITLE
Created property and unit counts for individual programs

### PR DESCRIPTION
**Pull request by Woliver01**
@ptatian Please review.

### CODE REVIEW

**Comment by ptatian** [comment]
Thanks, @Woliver01. This is a good start. A few things to fix. There's a variable name misspelling that is causing an uninitialized variable message. 

```
NOTE: Variable s202_1_AssitedUnits is uninitialized.
```

Also, the if/then statements are basically right but we want to assign the 0/1 values to the *same* variable. So, it should be

```
	if s8_all_assistedunits > 0 
	then s8_activeunits = 1;
	else s8_activeunits = 0;
	
	if s202_all_assistedunits > 0
	then s202_activeunits = 1;
	else s202_activeunits = 0;

        ...
```

Then, in reviewing the data, my assumption that adding the S8 units together wouldn't double-count didn't quite pan out. There are a few cases where you end up with more than the units in the entire property, as reported in *TotalUnits*. So, we need to make a slight adjustment to the code so that the number of assisted units does not exceed *TotalUnits*. 

```
	s8_all_assistedunits=min(sum(s8_1_AssistedUnits, s8_2_AssistedUnits),TotalUnits);
	s202_all_assistedunits=min(sum(s202_1_AssitedUnits, s202_2_AssistedUnits),TotalUnits);
        ...
```

However, in checking the above I also realized there's a mistake in **RegHsg.Natlpres_activeandinc_prop** that we need to fix. The S236 assisted unit counts were created as character variables, not numeric variables. I'll create a separate issue for that fix. 

Please make the above changes and commit and then we can go on to the next step.

**Comment by Woliver01** [comment]
@ptatian working through these changes now.

**Comment by Woliver01** [comment]
@ptatian please review.

**Comment by ptatian** [comment]
@Woliver01 Looks good. Please carry on with step 2 in issue #39.  

One small thing. Noticed that the program name needs to be updated in the program header. Thx.

**Pull request merged**
